"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { persistor, store } from "./store";
import { PersistGate } from "redux-persist/integration/react";
import BlogProvider from "./provider/BlogContext";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <BlogProvider>
              <ToastContainer />
              {children}
            </BlogProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
